-- this file is generated by xresloader, please don't edit it.

return {
  [1] = {
    count = 3,
    data_source = {
      {
        count = 3,
        file = "b8af9bb6f35231297dcf553e984e193ff4266b5a784191e5ab6baba2f760e166",
        sheet = "70ac754c3e097b4114964e6a4ec0398b030817617166f8ebf2cd5608a5026a34",
      },
    },
    data_ver = "1.0.0.0",
    description = "b741684279f664b9aa427c27ec2c76529c908834d322a737a7dfabfd6dc425ea",
    hash_code = "sha256:dd55e67e5c1312ca507fedd631c54b8c1266ab82859ed36bd535db90ac36a95f",
    xres_ver = "dev",
  },
  [2] = "arr_in_arr_cfg",
  arr_in_arr_cfg = {
    {
      arr = {
        {
          int_arr = {
            101,
            102,
          },
          name = "第一个-A",
          str_arr = {
            "啦啦啦啦",
            "嘞嘞嘞嘞",
          },
        },
        {
          int_arr = {
            111,
            112,
          },
          name = "第一个-B",
          str_arr = {
            "嘟嘟嘟嘟",
            "嚓嚓嚓嚓",
          },
        },
      },
      id = 10001,
      test_map_is = {
        [10] = "Map嵌套模式[0].value",
        [11] = "Map嵌套模式[1].value",
      },
      test_map_sm = {
        ["aa"] = {
          id = 111,
          level = "112",
        },
        ["特殊:字符"] = {
          id = 121,
          level = "122",
        },
      },
      test_plain_enum_arr = {
        10001,
        10001,
        10001,
      },
      test_plain_int_arr = {
        1,
        2,
        3,
      },
      test_plain_msg = {
        test_id_1 = 1,
        test_id_2 = 2,
      },
      test_plain_msg_arr = {
        {
          test_id_1 = 1,
          test_id_2 = 2,
        },
        {
          test_id_1 = 3,
          test_id_2 = 4,
        },
        {
          test_id_1 = 5,
          test_id_2 = 6,
        },
      },
    },
    {
      arr = {
        {
          int_arr = {
            201,
            202,
          },
          name = "测试项-A",
          str_arr = {
            "biubiubiubiu",
            "唰唰唰唰",
          },
        },
        {
          int_arr = {
            211,
            212,
          },
          name = "测试项-B",
          str_arr = {
            "哦哦哦哦",
            "哈哈哈哈",
          },
        },
      },
      id = 10002,
      test_map_is = {
        [20] = "Map嵌套模式[0].value",
        [21] = "Map嵌套模式[1].value",
      },
      test_map_sm = {
        ["ba"] = {
          id = 211,
          level = "212",
        },
        ["特殊.字符"] = {
          id = 221,
          level = "222",
        },
      },
      test_plain_enum_arr = {
        10101,
        10101,
        10101,
      },
      test_plain_int_arr = {
        4,
        5,
        6,
      },
      test_plain_msg = {
        test_id_1 = 3,
        test_id_2 = 4,
        test_id_3 = 5,
      },
      test_plain_msg_arr = {
        {
          test_id_1 = 7,
          test_id_2 = 8,
        },
        {
          test_id_1 = 9,
          test_id_2 = 10,
        },
      },
    },
    {
      arr = {
        {
          int_arr = {
            301,
            0,
          },
          name = "测试项-C",
        },
        {
          int_arr = {
            0,
            311,
          },
          name = "测试项-B",
          str_arr = {
            "哦哦哦哦",
          },
        },
      },
      id = 10003,
      test_map_is = {
        [30] = "Map嵌套模式[0].value",
        [31] = "Map嵌套模式[1].value",
      },
      test_map_sm = {
        ["ca"] = {
          id = 311,
          level = "312",
        },
        ["cb"] = {
          id = 321,
          level = "322",
        },
      },
      test_plain_enum_arr = {
        10001,
        10001,
        10001,
      },
      test_plain_int_arr = {
        7,
        8,
        9,
      },
      test_plain_msg = {
        test_id_1 = 6,
      },
      test_plain_msg_arr = {
        {
          test_id_1 = 11,
          test_id_2 = 12,
        },
      },
    },
  },
}