module("ProtoEnums.Kind", package.seeall)
-- this file is generated by xresloader, please don't edit it.

local const_res = {
  arr_in_arr = {
    test_nested_enum = {
      EN_TEST_NESTED_ENUM_VAL_1 = 0,
      EN_TEST_NESTED_ENUM_VAL_2 = 123,
    },
    test_nested_message = {
      test_nested_enum = {
        EN_TEST_NESTED_MESSAGE_ENUM_VAL_1 = 0,
        EN_TEST_NESTED_MESSAGE_ENUM_VAL_2 = 123,
      },
      test_onof = {
        kTestNestedMessageInfoRole = 11,
        kTestNestedMessageRoleUpgradeCfg = 12,
      },
    },
    test_onof = {
      kTestInfoRole = 11,
      kTestRoleUpgradeCfg = 12,
    },
  },
  cost_type = {
    EN_CT_UNKNOWN = 0,
    EN_CT_MONEY = 10001,
    EN_CT_DIAMOND = 10101,
  },
  game_const_config = {
    EN_GCC_UNKNOWN = 0,
    EN_GCC_FORMULAR_TYPE_MASK = 10,
    EN_GCC_RANDOM_RANGE_UNIT = 10,
    EN_GCC_SOLDIER_TYPE_MASK = 100,
    EN_GCC_CAMERA_OFFSET = 268,
    EN_GCC_SCREEN_HEIGHT = 640,
    EN_GCC_LEVEL_LIMIT = 999,
    EN_GCC_ACTIVITY_TYPE_MASK = 1000,
    EN_GCC_SCREEN_WIDTH = 1136,
    EN_GCC_PERCENT_BASE = 10000,
    EN_GCC_RESOURCE_MAX_LIMIT = 9999999,
  },
  org = {
    xresloader = {
      ue = {
      },
    },
  },
}


game_const_config = const_res.game_const_config
cost_type = const_res.cost_type
org = const_res.org
arr_in_arr = const_res.arr_in_arr
