-- this file is generated by xresloader, please don't edit it.

return {
  [1] = {
    count = 2,
    data_source = {
      {
        count = 2,
        file = "b8af9bb6f35231297dcf553e984e193ff4266b5a784191e5ab6baba2f760e166",
        sheet = "fea1727ebf0dc3a369193e2d07ebf3c9fb34c14439678ccd7540f313ec3e6b28",
      },
    },
    data_ver = "1.0.0.0",
    hash_code = "sha256:e99feb6b80a35127a916429bb5f48c7e15bd16e198bad71422598eb47765aa67",
    xres_ver = "2.20.0",
  },
  [2] = "outer_alias_message",
  outer_alias_message = {
    {
      iId = 1,
      inners = {
        {
          iType = 11000000,
          paramList = {
            111,
            112,
            113,
          },
        },
        {
          iType = 12,
          paramList = {
            121,
            122,
            123,
          },
        },
        {
          iType = 13,
          paramList = {
            131,
            132,
            133,
          },
        },
      },
      nest_int = {
        141,
        142,
        143,
      },
    },
    {
      iId = 2,
      inners = {
        {
          iType = 21000000,
          paramList = {
            211,
            212,
            213,
          },
        },
        {
          iType = 0,
          paramList = {
            221,
            222,
            0,
          },
        },
        {
          iType = 23,
          paramList = {
            231,
            232,
          },
        },
      },
      nest_int = {
        241,
        242,
        0,
      },
    },
  },
}