// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb_header_v3.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_pb_5fheader_5fv3_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_pb_5fheader_5fv3_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_pb_5fheader_5fv3_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_pb_5fheader_5fv3_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_pb_5fheader_5fv3_2eproto;
namespace org {
namespace xresloader {
namespace pb {
class xresloader_datablocks;
class xresloader_datablocksDefaultTypeInternal;
extern xresloader_datablocksDefaultTypeInternal _xresloader_datablocks_default_instance_;
class xresloader_header;
class xresloader_headerDefaultTypeInternal;
extern xresloader_headerDefaultTypeInternal _xresloader_header_default_instance_;
}  // namespace pb
}  // namespace xresloader
}  // namespace org
PROTOBUF_NAMESPACE_OPEN
template<> ::org::xresloader::pb::xresloader_datablocks* Arena::CreateMaybeMessage<::org::xresloader::pb::xresloader_datablocks>(Arena*);
template<> ::org::xresloader::pb::xresloader_header* Arena::CreateMaybeMessage<::org::xresloader::pb::xresloader_header>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace org {
namespace xresloader {
namespace pb {

// ===================================================================

class xresloader_header PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:org.xresloader.pb.xresloader_header) */ {
 public:
  inline xresloader_header() : xresloader_header(nullptr) {};
  virtual ~xresloader_header();

  xresloader_header(const xresloader_header& from);
  xresloader_header(xresloader_header&& from) noexcept
    : xresloader_header() {
    *this = ::std::move(from);
  }

  inline xresloader_header& operator=(const xresloader_header& from) {
    CopyFrom(from);
    return *this;
  }
  inline xresloader_header& operator=(xresloader_header&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const xresloader_header& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const xresloader_header* internal_default_instance() {
    return reinterpret_cast<const xresloader_header*>(
               &_xresloader_header_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(xresloader_header& a, xresloader_header& b) {
    a.Swap(&b);
  }
  inline void Swap(xresloader_header* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(xresloader_header* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline xresloader_header* New() const final {
    return CreateMaybeMessage<xresloader_header>(nullptr);
  }

  xresloader_header* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<xresloader_header>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const xresloader_header& from);
  void MergeFrom(const xresloader_header& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(xresloader_header* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "org.xresloader.pb.xresloader_header";
  }
  protected:
  explicit xresloader_header(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_pb_5fheader_5fv3_2eproto);
    return ::descriptor_table_pb_5fheader_5fv3_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXresVerFieldNumber = 1,
    kDataVerFieldNumber = 2,
    kHashCodeFieldNumber = 4,
    kDescriptionFieldNumber = 5,
    kCountFieldNumber = 3,
  };
  // string xres_ver = 1;
  void clear_xres_ver();
  const std::string& xres_ver() const;
  void set_xres_ver(const std::string& value);
  void set_xres_ver(std::string&& value);
  void set_xres_ver(const char* value);
  void set_xres_ver(const char* value, size_t size);
  std::string* mutable_xres_ver();
  std::string* release_xres_ver();
  void set_allocated_xres_ver(std::string* xres_ver);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_xres_ver();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_xres_ver(
      std::string* xres_ver);
  private:
  const std::string& _internal_xres_ver() const;
  void _internal_set_xres_ver(const std::string& value);
  std::string* _internal_mutable_xres_ver();
  public:

  // string data_ver = 2;
  void clear_data_ver();
  const std::string& data_ver() const;
  void set_data_ver(const std::string& value);
  void set_data_ver(std::string&& value);
  void set_data_ver(const char* value);
  void set_data_ver(const char* value, size_t size);
  std::string* mutable_data_ver();
  std::string* release_data_ver();
  void set_allocated_data_ver(std::string* data_ver);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_data_ver();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_data_ver(
      std::string* data_ver);
  private:
  const std::string& _internal_data_ver() const;
  void _internal_set_data_ver(const std::string& value);
  std::string* _internal_mutable_data_ver();
  public:

  // string hash_code = 4;
  void clear_hash_code();
  const std::string& hash_code() const;
  void set_hash_code(const std::string& value);
  void set_hash_code(std::string&& value);
  void set_hash_code(const char* value);
  void set_hash_code(const char* value, size_t size);
  std::string* mutable_hash_code();
  std::string* release_hash_code();
  void set_allocated_hash_code(std::string* hash_code);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_hash_code();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_hash_code(
      std::string* hash_code);
  private:
  const std::string& _internal_hash_code() const;
  void _internal_set_hash_code(const std::string& value);
  std::string* _internal_mutable_hash_code();
  public:

  // string description = 5;
  void clear_description();
  const std::string& description() const;
  void set_description(const std::string& value);
  void set_description(std::string&& value);
  void set_description(const char* value);
  void set_description(const char* value, size_t size);
  std::string* mutable_description();
  std::string* release_description();
  void set_allocated_description(std::string* description);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_description();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_description(
      std::string* description);
  private:
  const std::string& _internal_description() const;
  void _internal_set_description(const std::string& value);
  std::string* _internal_mutable_description();
  public:

  // uint32 count = 3;
  void clear_count();
  ::PROTOBUF_NAMESPACE_ID::uint32 count() const;
  void set_count(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_count() const;
  void _internal_set_count(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:org.xresloader.pb.xresloader_header)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr xres_ver_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr data_ver_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr hash_code_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr description_;
  ::PROTOBUF_NAMESPACE_ID::uint32 count_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_pb_5fheader_5fv3_2eproto;
};
// -------------------------------------------------------------------

class xresloader_datablocks PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:org.xresloader.pb.xresloader_datablocks) */ {
 public:
  inline xresloader_datablocks() : xresloader_datablocks(nullptr) {};
  virtual ~xresloader_datablocks();

  xresloader_datablocks(const xresloader_datablocks& from);
  xresloader_datablocks(xresloader_datablocks&& from) noexcept
    : xresloader_datablocks() {
    *this = ::std::move(from);
  }

  inline xresloader_datablocks& operator=(const xresloader_datablocks& from) {
    CopyFrom(from);
    return *this;
  }
  inline xresloader_datablocks& operator=(xresloader_datablocks&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const xresloader_datablocks& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const xresloader_datablocks* internal_default_instance() {
    return reinterpret_cast<const xresloader_datablocks*>(
               &_xresloader_datablocks_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(xresloader_datablocks& a, xresloader_datablocks& b) {
    a.Swap(&b);
  }
  inline void Swap(xresloader_datablocks* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(xresloader_datablocks* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline xresloader_datablocks* New() const final {
    return CreateMaybeMessage<xresloader_datablocks>(nullptr);
  }

  xresloader_datablocks* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<xresloader_datablocks>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const xresloader_datablocks& from);
  void MergeFrom(const xresloader_datablocks& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(xresloader_datablocks* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "org.xresloader.pb.xresloader_datablocks";
  }
  protected:
  explicit xresloader_datablocks(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_pb_5fheader_5fv3_2eproto);
    return ::descriptor_table_pb_5fheader_5fv3_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDataBlockFieldNumber = 2,
    kDataMessageTypeFieldNumber = 3,
    kHeaderFieldNumber = 1,
  };
  // repeated bytes data_block = 2;
  int data_block_size() const;
  private:
  int _internal_data_block_size() const;
  public:
  void clear_data_block();
  const std::string& data_block(int index) const;
  std::string* mutable_data_block(int index);
  void set_data_block(int index, const std::string& value);
  void set_data_block(int index, std::string&& value);
  void set_data_block(int index, const char* value);
  void set_data_block(int index, const void* value, size_t size);
  std::string* add_data_block();
  void add_data_block(const std::string& value);
  void add_data_block(std::string&& value);
  void add_data_block(const char* value);
  void add_data_block(const void* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& data_block() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_data_block();
  private:
  const std::string& _internal_data_block(int index) const;
  std::string* _internal_add_data_block();
  public:

  // string data_message_type = 3;
  void clear_data_message_type();
  const std::string& data_message_type() const;
  void set_data_message_type(const std::string& value);
  void set_data_message_type(std::string&& value);
  void set_data_message_type(const char* value);
  void set_data_message_type(const char* value, size_t size);
  std::string* mutable_data_message_type();
  std::string* release_data_message_type();
  void set_allocated_data_message_type(std::string* data_message_type);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_data_message_type();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_data_message_type(
      std::string* data_message_type);
  private:
  const std::string& _internal_data_message_type() const;
  void _internal_set_data_message_type(const std::string& value);
  std::string* _internal_mutable_data_message_type();
  public:

  // .org.xresloader.pb.xresloader_header header = 1;
  bool has_header() const;
  private:
  bool _internal_has_header() const;
  public:
  void clear_header();
  const ::org::xresloader::pb::xresloader_header& header() const;
  ::org::xresloader::pb::xresloader_header* release_header();
  ::org::xresloader::pb::xresloader_header* mutable_header();
  void set_allocated_header(::org::xresloader::pb::xresloader_header* header);
  private:
  const ::org::xresloader::pb::xresloader_header& _internal_header() const;
  ::org::xresloader::pb::xresloader_header* _internal_mutable_header();
  public:
  void unsafe_arena_set_allocated_header(
      ::org::xresloader::pb::xresloader_header* header);
  ::org::xresloader::pb::xresloader_header* unsafe_arena_release_header();

  // @@protoc_insertion_point(class_scope:org.xresloader.pb.xresloader_datablocks)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> data_block_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr data_message_type_;
  ::org::xresloader::pb::xresloader_header* header_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_pb_5fheader_5fv3_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// xresloader_header

// string xres_ver = 1;
inline void xresloader_header::clear_xres_ver() {
  xres_ver_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& xresloader_header::xres_ver() const {
  // @@protoc_insertion_point(field_get:org.xresloader.pb.xresloader_header.xres_ver)
  return _internal_xres_ver();
}
inline void xresloader_header::set_xres_ver(const std::string& value) {
  _internal_set_xres_ver(value);
  // @@protoc_insertion_point(field_set:org.xresloader.pb.xresloader_header.xres_ver)
}
inline std::string* xresloader_header::mutable_xres_ver() {
  // @@protoc_insertion_point(field_mutable:org.xresloader.pb.xresloader_header.xres_ver)
  return _internal_mutable_xres_ver();
}
inline const std::string& xresloader_header::_internal_xres_ver() const {
  return xres_ver_.Get();
}
inline void xresloader_header::_internal_set_xres_ver(const std::string& value) {
  
  xres_ver_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void xresloader_header::set_xres_ver(std::string&& value) {
  
  xres_ver_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:org.xresloader.pb.xresloader_header.xres_ver)
}
inline void xresloader_header::set_xres_ver(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  xres_ver_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:org.xresloader.pb.xresloader_header.xres_ver)
}
inline void xresloader_header::set_xres_ver(const char* value,
    size_t size) {
  
  xres_ver_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:org.xresloader.pb.xresloader_header.xres_ver)
}
inline std::string* xresloader_header::_internal_mutable_xres_ver() {
  
  return xres_ver_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* xresloader_header::release_xres_ver() {
  // @@protoc_insertion_point(field_release:org.xresloader.pb.xresloader_header.xres_ver)
  return xres_ver_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void xresloader_header::set_allocated_xres_ver(std::string* xres_ver) {
  if (xres_ver != nullptr) {
    
  } else {
    
  }
  xres_ver_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), xres_ver,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:org.xresloader.pb.xresloader_header.xres_ver)
}
inline std::string* xresloader_header::unsafe_arena_release_xres_ver() {
  // @@protoc_insertion_point(field_unsafe_arena_release:org.xresloader.pb.xresloader_header.xres_ver)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return xres_ver_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void xresloader_header::unsafe_arena_set_allocated_xres_ver(
    std::string* xres_ver) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (xres_ver != nullptr) {
    
  } else {
    
  }
  xres_ver_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      xres_ver, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:org.xresloader.pb.xresloader_header.xres_ver)
}

// string data_ver = 2;
inline void xresloader_header::clear_data_ver() {
  data_ver_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& xresloader_header::data_ver() const {
  // @@protoc_insertion_point(field_get:org.xresloader.pb.xresloader_header.data_ver)
  return _internal_data_ver();
}
inline void xresloader_header::set_data_ver(const std::string& value) {
  _internal_set_data_ver(value);
  // @@protoc_insertion_point(field_set:org.xresloader.pb.xresloader_header.data_ver)
}
inline std::string* xresloader_header::mutable_data_ver() {
  // @@protoc_insertion_point(field_mutable:org.xresloader.pb.xresloader_header.data_ver)
  return _internal_mutable_data_ver();
}
inline const std::string& xresloader_header::_internal_data_ver() const {
  return data_ver_.Get();
}
inline void xresloader_header::_internal_set_data_ver(const std::string& value) {
  
  data_ver_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void xresloader_header::set_data_ver(std::string&& value) {
  
  data_ver_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:org.xresloader.pb.xresloader_header.data_ver)
}
inline void xresloader_header::set_data_ver(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  data_ver_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:org.xresloader.pb.xresloader_header.data_ver)
}
inline void xresloader_header::set_data_ver(const char* value,
    size_t size) {
  
  data_ver_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:org.xresloader.pb.xresloader_header.data_ver)
}
inline std::string* xresloader_header::_internal_mutable_data_ver() {
  
  return data_ver_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* xresloader_header::release_data_ver() {
  // @@protoc_insertion_point(field_release:org.xresloader.pb.xresloader_header.data_ver)
  return data_ver_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void xresloader_header::set_allocated_data_ver(std::string* data_ver) {
  if (data_ver != nullptr) {
    
  } else {
    
  }
  data_ver_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), data_ver,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:org.xresloader.pb.xresloader_header.data_ver)
}
inline std::string* xresloader_header::unsafe_arena_release_data_ver() {
  // @@protoc_insertion_point(field_unsafe_arena_release:org.xresloader.pb.xresloader_header.data_ver)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return data_ver_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void xresloader_header::unsafe_arena_set_allocated_data_ver(
    std::string* data_ver) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (data_ver != nullptr) {
    
  } else {
    
  }
  data_ver_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      data_ver, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:org.xresloader.pb.xresloader_header.data_ver)
}

// uint32 count = 3;
inline void xresloader_header::clear_count() {
  count_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 xresloader_header::_internal_count() const {
  return count_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 xresloader_header::count() const {
  // @@protoc_insertion_point(field_get:org.xresloader.pb.xresloader_header.count)
  return _internal_count();
}
inline void xresloader_header::_internal_set_count(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  count_ = value;
}
inline void xresloader_header::set_count(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_count(value);
  // @@protoc_insertion_point(field_set:org.xresloader.pb.xresloader_header.count)
}

// string hash_code = 4;
inline void xresloader_header::clear_hash_code() {
  hash_code_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& xresloader_header::hash_code() const {
  // @@protoc_insertion_point(field_get:org.xresloader.pb.xresloader_header.hash_code)
  return _internal_hash_code();
}
inline void xresloader_header::set_hash_code(const std::string& value) {
  _internal_set_hash_code(value);
  // @@protoc_insertion_point(field_set:org.xresloader.pb.xresloader_header.hash_code)
}
inline std::string* xresloader_header::mutable_hash_code() {
  // @@protoc_insertion_point(field_mutable:org.xresloader.pb.xresloader_header.hash_code)
  return _internal_mutable_hash_code();
}
inline const std::string& xresloader_header::_internal_hash_code() const {
  return hash_code_.Get();
}
inline void xresloader_header::_internal_set_hash_code(const std::string& value) {
  
  hash_code_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void xresloader_header::set_hash_code(std::string&& value) {
  
  hash_code_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:org.xresloader.pb.xresloader_header.hash_code)
}
inline void xresloader_header::set_hash_code(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  hash_code_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:org.xresloader.pb.xresloader_header.hash_code)
}
inline void xresloader_header::set_hash_code(const char* value,
    size_t size) {
  
  hash_code_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:org.xresloader.pb.xresloader_header.hash_code)
}
inline std::string* xresloader_header::_internal_mutable_hash_code() {
  
  return hash_code_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* xresloader_header::release_hash_code() {
  // @@protoc_insertion_point(field_release:org.xresloader.pb.xresloader_header.hash_code)
  return hash_code_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void xresloader_header::set_allocated_hash_code(std::string* hash_code) {
  if (hash_code != nullptr) {
    
  } else {
    
  }
  hash_code_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), hash_code,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:org.xresloader.pb.xresloader_header.hash_code)
}
inline std::string* xresloader_header::unsafe_arena_release_hash_code() {
  // @@protoc_insertion_point(field_unsafe_arena_release:org.xresloader.pb.xresloader_header.hash_code)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return hash_code_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void xresloader_header::unsafe_arena_set_allocated_hash_code(
    std::string* hash_code) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (hash_code != nullptr) {
    
  } else {
    
  }
  hash_code_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      hash_code, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:org.xresloader.pb.xresloader_header.hash_code)
}

// string description = 5;
inline void xresloader_header::clear_description() {
  description_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& xresloader_header::description() const {
  // @@protoc_insertion_point(field_get:org.xresloader.pb.xresloader_header.description)
  return _internal_description();
}
inline void xresloader_header::set_description(const std::string& value) {
  _internal_set_description(value);
  // @@protoc_insertion_point(field_set:org.xresloader.pb.xresloader_header.description)
}
inline std::string* xresloader_header::mutable_description() {
  // @@protoc_insertion_point(field_mutable:org.xresloader.pb.xresloader_header.description)
  return _internal_mutable_description();
}
inline const std::string& xresloader_header::_internal_description() const {
  return description_.Get();
}
inline void xresloader_header::_internal_set_description(const std::string& value) {
  
  description_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void xresloader_header::set_description(std::string&& value) {
  
  description_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:org.xresloader.pb.xresloader_header.description)
}
inline void xresloader_header::set_description(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  description_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:org.xresloader.pb.xresloader_header.description)
}
inline void xresloader_header::set_description(const char* value,
    size_t size) {
  
  description_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:org.xresloader.pb.xresloader_header.description)
}
inline std::string* xresloader_header::_internal_mutable_description() {
  
  return description_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* xresloader_header::release_description() {
  // @@protoc_insertion_point(field_release:org.xresloader.pb.xresloader_header.description)
  return description_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void xresloader_header::set_allocated_description(std::string* description) {
  if (description != nullptr) {
    
  } else {
    
  }
  description_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), description,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:org.xresloader.pb.xresloader_header.description)
}
inline std::string* xresloader_header::unsafe_arena_release_description() {
  // @@protoc_insertion_point(field_unsafe_arena_release:org.xresloader.pb.xresloader_header.description)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return description_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void xresloader_header::unsafe_arena_set_allocated_description(
    std::string* description) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (description != nullptr) {
    
  } else {
    
  }
  description_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      description, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:org.xresloader.pb.xresloader_header.description)
}

// -------------------------------------------------------------------

// xresloader_datablocks

// .org.xresloader.pb.xresloader_header header = 1;
inline bool xresloader_datablocks::_internal_has_header() const {
  return this != internal_default_instance() && header_ != nullptr;
}
inline bool xresloader_datablocks::has_header() const {
  return _internal_has_header();
}
inline void xresloader_datablocks::clear_header() {
  if (GetArena() == nullptr && header_ != nullptr) {
    delete header_;
  }
  header_ = nullptr;
}
inline const ::org::xresloader::pb::xresloader_header& xresloader_datablocks::_internal_header() const {
  const ::org::xresloader::pb::xresloader_header* p = header_;
  return p != nullptr ? *p : *reinterpret_cast<const ::org::xresloader::pb::xresloader_header*>(
      &::org::xresloader::pb::_xresloader_header_default_instance_);
}
inline const ::org::xresloader::pb::xresloader_header& xresloader_datablocks::header() const {
  // @@protoc_insertion_point(field_get:org.xresloader.pb.xresloader_datablocks.header)
  return _internal_header();
}
inline void xresloader_datablocks::unsafe_arena_set_allocated_header(
    ::org::xresloader::pb::xresloader_header* header) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  header_ = header;
  if (header) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:org.xresloader.pb.xresloader_datablocks.header)
}
inline ::org::xresloader::pb::xresloader_header* xresloader_datablocks::release_header() {
  auto temp = unsafe_arena_release_header();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::org::xresloader::pb::xresloader_header* xresloader_datablocks::unsafe_arena_release_header() {
  // @@protoc_insertion_point(field_release:org.xresloader.pb.xresloader_datablocks.header)
  
  ::org::xresloader::pb::xresloader_header* temp = header_;
  header_ = nullptr;
  return temp;
}
inline ::org::xresloader::pb::xresloader_header* xresloader_datablocks::_internal_mutable_header() {
  
  if (header_ == nullptr) {
    auto* p = CreateMaybeMessage<::org::xresloader::pb::xresloader_header>(GetArena());
    header_ = p;
  }
  return header_;
}
inline ::org::xresloader::pb::xresloader_header* xresloader_datablocks::mutable_header() {
  // @@protoc_insertion_point(field_mutable:org.xresloader.pb.xresloader_datablocks.header)
  return _internal_mutable_header();
}
inline void xresloader_datablocks::set_allocated_header(::org::xresloader::pb::xresloader_header* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete header_;
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(header);
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    
  } else {
    
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:org.xresloader.pb.xresloader_datablocks.header)
}

// repeated bytes data_block = 2;
inline int xresloader_datablocks::_internal_data_block_size() const {
  return data_block_.size();
}
inline int xresloader_datablocks::data_block_size() const {
  return _internal_data_block_size();
}
inline void xresloader_datablocks::clear_data_block() {
  data_block_.Clear();
}
inline std::string* xresloader_datablocks::add_data_block() {
  // @@protoc_insertion_point(field_add_mutable:org.xresloader.pb.xresloader_datablocks.data_block)
  return _internal_add_data_block();
}
inline const std::string& xresloader_datablocks::_internal_data_block(int index) const {
  return data_block_.Get(index);
}
inline const std::string& xresloader_datablocks::data_block(int index) const {
  // @@protoc_insertion_point(field_get:org.xresloader.pb.xresloader_datablocks.data_block)
  return _internal_data_block(index);
}
inline std::string* xresloader_datablocks::mutable_data_block(int index) {
  // @@protoc_insertion_point(field_mutable:org.xresloader.pb.xresloader_datablocks.data_block)
  return data_block_.Mutable(index);
}
inline void xresloader_datablocks::set_data_block(int index, const std::string& value) {
  // @@protoc_insertion_point(field_set:org.xresloader.pb.xresloader_datablocks.data_block)
  data_block_.Mutable(index)->assign(value);
}
inline void xresloader_datablocks::set_data_block(int index, std::string&& value) {
  // @@protoc_insertion_point(field_set:org.xresloader.pb.xresloader_datablocks.data_block)
  data_block_.Mutable(index)->assign(std::move(value));
}
inline void xresloader_datablocks::set_data_block(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  data_block_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:org.xresloader.pb.xresloader_datablocks.data_block)
}
inline void xresloader_datablocks::set_data_block(int index, const void* value, size_t size) {
  data_block_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:org.xresloader.pb.xresloader_datablocks.data_block)
}
inline std::string* xresloader_datablocks::_internal_add_data_block() {
  return data_block_.Add();
}
inline void xresloader_datablocks::add_data_block(const std::string& value) {
  data_block_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:org.xresloader.pb.xresloader_datablocks.data_block)
}
inline void xresloader_datablocks::add_data_block(std::string&& value) {
  data_block_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:org.xresloader.pb.xresloader_datablocks.data_block)
}
inline void xresloader_datablocks::add_data_block(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  data_block_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:org.xresloader.pb.xresloader_datablocks.data_block)
}
inline void xresloader_datablocks::add_data_block(const void* value, size_t size) {
  data_block_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:org.xresloader.pb.xresloader_datablocks.data_block)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
xresloader_datablocks::data_block() const {
  // @@protoc_insertion_point(field_list:org.xresloader.pb.xresloader_datablocks.data_block)
  return data_block_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
xresloader_datablocks::mutable_data_block() {
  // @@protoc_insertion_point(field_mutable_list:org.xresloader.pb.xresloader_datablocks.data_block)
  return &data_block_;
}

// string data_message_type = 3;
inline void xresloader_datablocks::clear_data_message_type() {
  data_message_type_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& xresloader_datablocks::data_message_type() const {
  // @@protoc_insertion_point(field_get:org.xresloader.pb.xresloader_datablocks.data_message_type)
  return _internal_data_message_type();
}
inline void xresloader_datablocks::set_data_message_type(const std::string& value) {
  _internal_set_data_message_type(value);
  // @@protoc_insertion_point(field_set:org.xresloader.pb.xresloader_datablocks.data_message_type)
}
inline std::string* xresloader_datablocks::mutable_data_message_type() {
  // @@protoc_insertion_point(field_mutable:org.xresloader.pb.xresloader_datablocks.data_message_type)
  return _internal_mutable_data_message_type();
}
inline const std::string& xresloader_datablocks::_internal_data_message_type() const {
  return data_message_type_.Get();
}
inline void xresloader_datablocks::_internal_set_data_message_type(const std::string& value) {
  
  data_message_type_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void xresloader_datablocks::set_data_message_type(std::string&& value) {
  
  data_message_type_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:org.xresloader.pb.xresloader_datablocks.data_message_type)
}
inline void xresloader_datablocks::set_data_message_type(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  data_message_type_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:org.xresloader.pb.xresloader_datablocks.data_message_type)
}
inline void xresloader_datablocks::set_data_message_type(const char* value,
    size_t size) {
  
  data_message_type_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:org.xresloader.pb.xresloader_datablocks.data_message_type)
}
inline std::string* xresloader_datablocks::_internal_mutable_data_message_type() {
  
  return data_message_type_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* xresloader_datablocks::release_data_message_type() {
  // @@protoc_insertion_point(field_release:org.xresloader.pb.xresloader_datablocks.data_message_type)
  return data_message_type_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void xresloader_datablocks::set_allocated_data_message_type(std::string* data_message_type) {
  if (data_message_type != nullptr) {
    
  } else {
    
  }
  data_message_type_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), data_message_type,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:org.xresloader.pb.xresloader_datablocks.data_message_type)
}
inline std::string* xresloader_datablocks::unsafe_arena_release_data_message_type() {
  // @@protoc_insertion_point(field_unsafe_arena_release:org.xresloader.pb.xresloader_datablocks.data_message_type)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return data_message_type_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void xresloader_datablocks::unsafe_arena_set_allocated_data_message_type(
    std::string* data_message_type) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (data_message_type != nullptr) {
    
  } else {
    
  }
  data_message_type_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      data_message_type, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:org.xresloader.pb.xresloader_datablocks.data_message_type)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace pb
}  // namespace xresloader
}  // namespace org

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_pb_5fheader_5fv3_2eproto
