-- this file is generated by xresloader, please don't edit it.

return {
  [1] = {
    count = 4,
    data_source = {
      {
        count = 4,
        file = "b8af9bb6f35231297dcf553e984e193ff4266b5a784191e5ab6baba2f760e166",
        sheet = "60a686f261898eb9b992070d5fe231ed4f8dbbfe72535b1bcfe7da57a22b147e",
      },
    },
    data_ver = "1.0.0.0",
    hash_code = "sha256:ef7f8c16749eaade17de51b58810cd06c57a8ec45cee89a8e450b4326e9eb2ae",
    xres_ver = "dev",
  },
  [2] = "field_alias_message",
  field_alias_message = {
    {
      id = 1,
      value = 1234,
    },
    {
      id = 2,
      value = 1234,
    },
    {
      id = 3,
      value = 5678,
    },
    {
      id = 4,
      value = 5678,
    },
  },
}