-- this file is generated by xresloader, please don't edit it.

return {
  [1] = {
    count = 2,
    data_source = {
      {
        count = 2,
        file = "资源转换示例.xlsx",
        sheet = "nest_alias",
      },
    },
    data_ver = "1.0.0.0",
    hash_code = "sha256:9a34adc87f8576240d82bfda90295964233c3e3102e3ca4889cea3d8b8b4157c",
    xres_ver = "2.18.0",
  },
  [2] = "outer_alias_message",
  outer_alias_message = {
    {
      iId = 1,
      inners = {
        {
          iType = 11,
          paramList = {
            111,
            112,
          },
        },
        {
          iType = 12,
          paramList = {
            121,
            122,
          },
        },
        {
          iType = 13,
          paramList = {
            131,
            132,
          },
        },
      },
    },
    {
      iId = 2,
      inners = {
        {
          iType = 21,
          paramList = {
            211,
            212,
          },
        },
        {
        },
        {
          iType = 23,
          paramList = {
            231,
          },
        },
      },
    },
  },
}